- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleListeningPost
  name: Listening Post Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-lpo
    antagPrototype: ListeningPost
    exclusiveAntag: true
  - type: ListeningPostRole
